title: Neil Collins # your name (or website title) here
logo: "/images/linkedin.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an analytical problem solver with a proven track record of success with organizations such as TD Ameritrade and Arizona State University. 
  My peers know me as an innovative thinker who can see the connections between different projects and initiatives, and that is why I am commonly 
  called upon to produce efficient, profit maximizing solutions, all of which are backed by ample data analysis.
  <br><br>
  I completed my B.S. in Economics at Arizona State University in May 2020 alongside a certificate in Applied Business Data Analytics, and I will complete
  my M.S. in Business Analytics at the University of Colorado Boulder in May 2021. I am currently open to both full and part time analytical positions due 
  to the schedule flexibility I have gained through online and hybrid courses as a result of COVID 19.

  <br><br>
  <a href="https://www.linkedin.com/in/neilcollins20/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
